import type { Metadata } from "next";
import { SITE } from "./constants";
import type { FaqItem, Product } from "@/services/cms/types";

const absolute = (path: string) => new URL(path, SITE.url).toString();

export interface SeoInput {
  title: string;
  description: string;
  /** Site-relative, e.g. "/products/aryabhata" */
  path: string;
  /**
   * Site-relative share image. Omit for the site-wide default.
   *
   * Pass `null` when the route ships its own `opengraph-image` file: setting
   * `openGraph.images` here would override it, which is exactly how the
   * per-kit product cards got replaced by the generic one.
   */
  image?: string | null;
  type?: "website" | "article";
  noIndex?: boolean;
}

/**
 * Generated by src/app/opengraph-image.tsx.
 *
 * Applied here rather than relying on the opengraph-image file convention to
 * cascade, because it does not: a metadata image file applies to pages in its
 * own directory, and a nested page that sets openGraph through `metadata`
 * — which every page here does, via this function — wins over an inherited
 * one. The result was a site-wide default that silently attached to nothing.
 * Naming the path explicitly is duller and actually works.
 *
 * /products/[slug] still overrides this with a per-kit card, because that
 * file sits in the same directory as the page it belongs to.
 */
const DEFAULT_OG_IMAGE = "/opengraph-image";

export function buildMetadata({
  title,
  description,
  path,
  image,
  type = "website",
  noIndex = false,
}: SeoInput): Metadata {
  const url = absolute(path);
  const ogImage = image === null ? null : absolute(image ?? DEFAULT_OG_IMAGE);

  return {
    title,
    description,
    /* Self-referential absolute canonical on every page. Faceted product URLs
       canonical back to /products — the single most important technical SEO
       decision here, because 8 facets combinatorially generate thousands of
       near-duplicate URLs that would otherwise eat the crawl budget. */
    alternates: { canonical: url },
    robots: noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },
    openGraph: {
      type,
      url,
      title,
      description,
      siteName: SITE.name,
      locale: SITE.locale,
      ...(ogImage
        ? { images: [{ url: ogImage, width: 1200, height: 630, alt: title }] }
        : {}),
    },
    twitter: {
      /* summary_large_image promises an image; every page now supplies one,
         either here or through its own opengraph-image file. Declaring the
         card type with no image is what produced the blank previews when a
         link was shared to a staffroom WhatsApp group. */
      card: "summary_large_image",
      title,
      description,
      ...(ogImage ? { images: [ogImage] } : {}),
    },
  };
}

/* --- Structured data ----------------------------------------------------- */

export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": ["Organization", "EducationalOrganization"],
    "@id": `${SITE.url}#organization`,
    name: SITE.name,
    url: SITE.url,
    slogan: SITE.tagline,
    description:
      "Gamified experiential learning kits and teacher training for schools in India.",
    telephone: SITE.phones,
    email: SITE.email,
    areaServed: { "@type": "State", name: "Gujarat" },
    /* sameAs is how a search engine ties these profiles to this organisation,
       so a URL that does not resolve is an active claim about the wrong
       entity. Confirmed accounts only — see constants.ts. */
    sameAs: [
      SITE.social.instagram,
      SITE.social.linkedin,
      SITE.social.youtube,
    ],
  };
}

export function websiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE.url}#website`,
    url: SITE.url,
    name: SITE.name,
    publisher: { "@id": `${SITE.url}#organization` },
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${SITE.url}/products?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  };
}

export function breadcrumbJsonLd(trail: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: absolute(item.path),
    })),
  };
}

/**
 * Product schema WITHOUT an `offers` block.
 *
 * Decision D7 makes products a portfolio with no public pricing. Emitting a
 * fabricated price to win a rich result would be lying to both Google and the
 * reader, so the offer is simply absent.
 */
export function productJsonLd(product: Product) {
  return {
    "@context": "https://schema.org",
    "@type": "Product",
    name: product.title,
    description: product.descriptionInstitutional,
    url: absolute(`/products/${product.slug}`),
    brand: { "@type": "Brand", name: SITE.name },
    category: "Educational game kit",
    audience: {
      "@type": "EducationalAudience",
      educationalRole: "student",
      suggestedMinAge: product.ageMin,
      suggestedMaxAge: product.ageMax,
    },
  };
}

export function faqJsonLd(items: FaqItem[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((f) => ({
      "@type": "Question",
      name: f.question,
      acceptedAnswer: { "@type": "Answer", text: f.answer },
    })),
  };
}
