import Image from "next/image";
import { cn } from "@/lib/utils";
import standing from "../../../public/brand/mascot-standing.webp";
import bust from "../../../public/brand/mascot-bust.webp";

/**
 * The brand mascot: a child whose head is a smiling die.
 *
 * WHY IT EXISTS AT ALL. The printed company profile a principal is handed is
 * illustrated in exactly this language - docs/brand-context.md describes its
 * imagery as "3D-rendered cartoon children with books, dice, and a globe;
 * playful, rounded, high-gloss". The site since moved to the flat isometric
 * vector world in blocks/heroes/khelverse. The mascot is the bridge back to
 * the paper, which is also the reason it must never appear in the same frame
 * as that world - glossy 3D and hard-faceted vector are two rendering
 * languages, and asking one viewport to hold both makes neither convincing.
 *
 * WHERE IT BELONGS. Places where a friendly face does work the copy cannot:
 * the moment after someone has submitted an enquiry, a dead end, the parent
 * hub. Nowhere near the partner logos, the impact numbers or the government
 * page - a cartoon beside a Ministry seal reads as dilution of the seal, and
 * beside an impact figure it quietly reclassifies it from audited to
 * illustrative. Keep the total under about four surfaces; a mascot that turns
 * up everywhere stops being a greeting and becomes wallpaper.
 *
 * FOLLOWS blocks/navigation/logo.tsx, NOT ui/media-frame.tsx, and that is
 * deliberate despite MediaFrame's docblock claiming every image goes through
 * it (which the logo, logo wall and press gallery already contradict).
 * MediaFrame is a ratio box: `fill` inside an aspect-* div with object-cover,
 * which is right for photography of unknown shape and wrong for a cut-out with
 * one fixed intrinsic ratio. Here the intrinsic dimensions ARE the layout.
 *
 * IT CANNOT BE MIRRORED. The t-shirt reads "Play", so scaleX(-1) turns the
 * wordmark into gibberish. A right-facing mascot is a new render, not a CSS
 * transform, which is why there is no `flipped` prop and should not be one.
 *
 * IT HAS NO CONTACT SHADOW. The supplied render appears to have one, but the
 * alpha beneath the feet is 0, so it never paints - the figure is a clean
 * cut-out and floats. Do not add a drop-shadow filter: it traces the whole
 * silhouette including the die head and reads as a sticker outline. Ground it
 * with layout instead, by sitting the feet on the bottom edge of a panel,
 * which is what every current placement does.
 *
 * NO DARK-MODE TREATMENT, unlike .logo-mark in globals.css. That tile exists
 * because the partner marks are flat dark ink drawn for white paper and go
 * illegible on a dark ground. The mascot is a full-colour figure carrying its
 * own internal contrast - purple shirt, tan shorts, blue shoes, pale die head
 * - and reads on both grounds unaided. A tile behind it would turn a cut-out
 * into a sticker and put back the white rectangle the logo pipeline exists to
 * remove.
 *
 * The artwork is generated by scripts/build-mascot.mjs from the full-fidelity
 * source at assets/source/mascot/standing.png. Read that script before
 * changing anything about the files here.
 */

/* Two crops of one render, the same split logo.tsx makes between the wordmark
   and the full lockup.

   `standing` is the whole figure. `bust` is head and folded arms, and exists
   because below roughly 96px the die head stops reading as a die - the front
   face carries a FACE, and the only pips are on the side face - so the whole
   figure collapses into a beige smudge. Anything small takes the bust. */
const CROP = {
  standing: { src: standing, label: "standing" },
  bust: { src: bust, label: "bust" },
} as const;

/* Static map, because Tailwind extracts class names at build time and an
   interpolated `w-${n}` produces no CSS at all - the same trap media-frame.tsx
   documents for its radius map.

   THE SCALE STOPS AT 256px ON PURPOSE. The master is 792px wide, which is
   every pixel of mascot that exists. 256 CSS px is 768 device px at a 3x
   ratio, so even the densest phone stays inside the master. An `xl` at 320px
   would ask the optimiser to upsample past it and return a file that is both
   larger and softer, which is the whole failure mode this cap prevents.

   `sizes` is a bare pixel hint with no vw token, matching logo.tsx. A vw here
   would be actively harmful: Next filters its candidate widths against
   deviceSizes[0] = 640, so `sizes="100vw"` floors every candidate at 640 and
   fetches ~38KB for a 96px slot. */
const SIZE = {
  sm: { className: "w-24", sizes: "96px" },
  md: { className: "w-40", sizes: "160px" },
  lg: { className: "w-64", sizes: "256px" },
} as const;

export function Mascot({
  crop = "standing",
  size = "md",
  alt,
  className,
}: {
  crop?: keyof typeof CROP;
  size?: keyof typeof SIZE;
  /**
   * OMIT THIS. Decorative is the default and should stay the answer.
   *
   * Every current placement sits beside copy that already says what the
   * mascot says, so announcing it adds nothing for a screen reader and one
   * more thing to listen past. Absent `alt` renders alt="" aria-hidden, which
   * is how media-frame.tsx handles its own decorative case.
   *
   * Inside a link, omit it unconditionally - the link carries the accessible
   * name and a duplicate alt makes the brand get announced twice (see the
   * same note in logo.tsx).
   *
   * If a placement ever genuinely needs one, the string must come from
   * getDictionary(), not a literal. Every route renders under [locale], and a
   * hardcoded English alt announces English on /gu/.
   */
  alt?: string;
  /**
   * Positioning and margins only.
   *
   * cn() merges through twMerge, so a width or height class passed here BEATS
   * the size map: `h-40` distorts the figure, and `w-full` desynchronises the
   * rendered width from the `sizes` hint above, which silently doubles what
   * gets downloaded. Change `size` instead.
   */
  className?: string;
}) {
  return (
    <Image
      src={CROP[crop].src}
      alt={alt ?? ""}
      aria-hidden={alt === undefined || undefined}
      sizes={SIZE[size].sizes}
      /* NO `priority`, and no prop to add one.

         The home page LCP element is the headline TEXT, which hero-home.tsx
         and docs/architecture/12-performance-strategy.md both state outright.
         `priority` injects a <link rel="preload" as="image"> into <head>,
         where it competes for the first round trips with the stylesheet and
         the preloaded sans font - the two resources that text LCP actually
         depends on. Preloading decoration ahead of them is the surest way to
         regress this page.

         Lazy everywhere is safe, including above the fold: browsers fetch an
         in-viewport lazy image in the first pass anyway, so the deferral only
         ever bites for images nobody has scrolled to.

         NO `placeholder="blur"` either. Next paints a blur placeholder as a
         background-image with background-size: cover behind the <img>, which
         for a cut-out on a transparent ground is a grey-pink smear in the
         shape of a rectangle the figure does not have. The intrinsic
         dimensions already reserve the space, so there is nothing to cover. */
      className={cn("h-auto", SIZE[size].className, className)}
    />
  );
}
